app:
  auth:
    accessTokenSecret: ${ACCESS_TOKEN_SECRET:${random.value}${random.value}}
    refreshTokenSecret: ${REFRESH_TOKEN_SECRET:${random.value}${random.value}}
    accessTokenExpirationDuration: PT10M
    refreshTokenExpirationDuration: P14DT0H
    accessTokenReissueDuration: PT5M
    refreshTokenReissueDuration: P1DT0H
