spring:
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-auth.yml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  h2:
    console:
      enabled: false
  data:
    web.pageable:
      default-page-size: 30
      max-page-size: 1000
      one-indexed-parameters: true
logging:
  level:
    root: info
